### ISSUE TITLE
Possible issue when creating dirs on different pages

### ISSUE THREAD

**Issue by ducasp** [fr3nd/msxhub#10]
Line 1129 of hub.c:

    created_dirs[0] = '\0';

This is clearing the created_dirs list every page interation, so, if there is dir created on page 1 and another one created on page 2 (for a package whose file list spans over 2 pages), the dir created on page 1 won't be stored, as saving the created dirs is done after all pages are processed.

My suggestion is that just moving it to line 1114, before the for loop to iterate all pages, will avoid this of occurring.

**Comment by fr3nd** [comment]
Good catch! it definitely looks like a bug that was difficult to find. I created #11 to fix it. I'll test it once I have some time and make a new release.

Thank you!
