### ISSUE TITLE
Upgrade a package reverts to the default installation path

### ISSUE THREAD

**Issue by cmilanf** [fr3nd/msxhub#15]
I use custom installation paths for the packages, but when I upgrade them, they are reverted to the default installation path.

Desired behavior would be the package manager realizes the software is installed in a custom directory and then use it for the upgrade.

Thanks for your work!

**Comment by fr3nd** [comment]
I don't use this feature very often, so I wasn't aware of this bug, but it seems to be easy to fix.

Can you try with this binary? It should work as expected.
[hub.zip](https://github.com/fr3nd/msxhub/files/5978111/hub.zip)

**Comment by cmilanf** [comment]
I just tried it and now it is working as expected. Thank you for fixing it so quickly! :D
