### ISSUE TITLE
Nbasic package issues server side

### ISSUE THREAD

**Issue by ducasp** [fr3nd/msxhub#19]
![FB_IMG_1666454594889](https://user-images.githubusercontent.com/13124200/197349538-e256952b-f7f1-4a84-8dcf-6d60c4869e6f.jpg)
Not sure if this is only on nbasic and only on that nbasic.bin file, at least the nbasic.bin file issue is easy to reproduce if you go to msxhub website and try to download nbasic.bin individual file and inspect the downloaded file you will see the same bad contents of the file. This has been reported by a msxhub user in Brazil, since there is not a server specific git and it doesn't seem to be a package issue (the zip file download ok and files there are correct), thought about opening an Ossie here. Thanks 🙂

**Comment by fr3nd** [comment]
Hi @ducasp 

Sorry for the late reply, but this should be fixed now :)

I have deployed a new release that fixes the download link.
