### ISSUE TITLE
SofaROM

### ISSUE THREAD

**Issue by Tulack** [fr3nd/msxhub#20]
[SofaROM v3.2]
https://www.louthrax.net/mgr/

Hola, la última versión de SofaRom es 3.2 . 
En https://msxhub.com tenéis la 2.6-1 .

Gracias.

**Comment by fr3nd** [comment]
Hi @Tulack 

Thank you for reporting this. I've updated the package to release 3.2. It should be available now.

For the next time, this repository may not be the most appropriate place to report this issue, as it's for the C source code of the `msxhub` program. Can you please post the issue in the https://github.com/fr3nd/msxhub-packages repository next time?

Also, if you feel adventurous, and you want to update the package yourself, feel free to edit the YAML file of the package directly:
* https://github.com/fr3nd/msxhub-packages/blob/master/packages/SOFAROM.yaml

Thank you!
