### ISSUE TITLE
Unable to download hub.com via hget or manually on the website

### ISSUE THREAD

**Issue by cristianoag** [fr3nd/msxhub#21]
Hi, we are unable to download the hub.com tool using hget. The MSX is connected to the net, but when using hget to download the tool, it detects a 9K file and never completes the download. You always have to cancel the operation, otherwise it never finishes.

![image](https://user-images.githubusercontent.com/48498602/227793982-1b266599-a5af-48ff-98b8-2362d80b0053.png)

When going to the website https://msxhub.com/start and clicking the download link. We get a file not found message. 

![image](https://user-images.githubusercontent.com/48498602/227794044-3856d33a-e1ea-4e2c-8732-aecf8165277b.png)
![image](https://user-images.githubusercontent.com/48498602/227794069-01c437ab-de4a-44ea-a55f-0f770cf4c91a.png)

Previous downloaded files are also not working anymore and are not downloading new packages. 

![image](https://user-images.githubusercontent.com/48498602/227794181-67f117ea-7871-4c1e-96e9-cfe73bee5f0f.png)

**Comment by fr3nd** [comment]
Hi @cristianoag 

Thank you for reporting the issue. Apparently, the latest release of `hub.com` was not properly packaged, and the binary was just a text file with `Not Found` text.

I've forced a new release version with no changes to fix the issue, and it should be working now. Please, let me know if you're still having issues.

Best
