### ISSUE TITLE
progress bar shows bytes, but labels the units as kilobytes

### ISSUE THREAD

**Issue by jedimatt42** [fr3nd/msxhub#3]
https://github.com/fr3nd/msxhub/blob/7fc9bd20d34a62b3f2a0034d1acd9953b6cd8a59/src/hub.c#L601

I don't think this 'K' makes any sense there... when downloading AKID.COM from 'kids' package, progress shows values as:  24576K,  should just be 24576  cause that's bytes, or 24K or 25K if you want to round up... since transfer blocks seem to be in 1024 byte chunks.  

Or just drop the 'K'

**Comment by fr3nd** [comment]
You're right... that's a silly mistake :man_facepalming: 

I think it'd make more sense to divide `bytes_written` by 1024 and keep the 'K'.

Thanks for reporting!
