### ISSUE TITLE
hub upgrade hub destroys hub

### ISSUE THREAD

**Issue by jedimatt42** [fr3nd/msxhub#8]
It is odd that 'hub' seems to be a package managed by hub. Under what circumstances can a user interact with the 'hub' package? It seems some special protection is required. 

`hub upgrade hub` deletes the files in the hub installation directory and then locks up.

This leaves things broken..  the hub\config directory is still there. 
To recover, I went back to the 'hget' instructions for installing hub, then ran hub configure, proceeding at the warning that config already exists.

**Comment by fr3nd** [comment]
Thanks for reporting! I'll investigate it and see how to fix it. I recall testing this feature in the past before releasing it and I think it was working, but I may be wrong...

Will post an update here once done.

**Comment by fr3nd** [comment]
@jedimatt42 I've tried to reproduce what you reported and I could not replicate it: 

![2020-02-09 18 29 56](https://user-images.githubusercontent.com/493065/74106874-c7449a80-4b6a-11ea-97d2-3fc7bba95fb0.jpg)

Did you actually have this problem or just assumed it would happen?

**Comment by jedimatt42** [comment]
I did **actually** experience the issue. 

I will try again. Maybe something incidentally fixed between the original version I had and what you have now? IDK what version I used to be on. I am on ver 1.0.2 currently.

It just worked fine this time. 
If it does happen, it is easy enough to recover from.
Unless you want to test all previous released versions, this can be closed.

**Comment by fr3nd** [comment]
I tested it with 1.0.2. Maybe there is something different wit your setup and mine?

I'll close the issue and keep an eye if it's reported again.

Thanks again for reporting this.
